#!/usr/bin/env bash
# Generate .env from the current host user so container UIDs/GIDs match yours
# (keeps bind-mounted workspace files owned by you, not root). Idempotent.
set -euo pipefail
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd "$( dirname "${SCRIPT_DIR}" )"

DISTRO="${1:-humble}"

if [ -f .env ]; then
    echo ".env already exists — leaving it untouched."
    echo "  (delete it and re-run 'make init' to regenerate.)"
    exit 0
fi

cat > .env <<ENV
# Auto-generated by scripts/init.sh — edit freely.
USER_NAME=${USER}
USER_UID=$(id -u)
USER_GID=$(id -g)

# Default distro when you don't pass DISTRO= to make.
ROS_DISTRO=${DISTRO}

# Optional: override the Dockerfile for a distro that needs bespoke steps,
# e.g. DOCKERFILE=Dockerfile.jazzy
# DOCKERFILE=Dockerfile

# Single shared data folder (bags, maps, calib, ...). Point at a big disk/NAS
# if you don't want data living inside the repo.
DATA_DIR=./data

# DDS / networking — must match across every ROS 2 participant on the network.
ROS_DOMAIN_ID=0
RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
CYCLONEDDS_URI=file:///home/${USER}/config/cyclonedds.xml

# colcon parallelism
PARALLEL_WORKERS=2
ENV

echo "Wrote .env for ${USER} (uid=$(id -u), gid=$(id -g), default distro=${DISTRO})."
